[workspace]
# TODO: enable after adding a license and setting CARGO_REGISTRY_TOKEN secret
publish = false
git_release_enable = true
git_release_type = "auto"
git_tag_enable = true
changelog_update = true
changelog_config = "cliff.toml"
semver_check = false
