name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-nextest
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: ./.github/actions/install-solc
      - run: cargo nextest run

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@cargo-nextest
      - uses: taiki-e/install-action@just
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: ./.github/actions/install-solc
      - run: just cov-check
